### ISSUE TITLE
Review lessons page 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/new-website#33]
Review lessons page: https://swc-new-website.netlify.app/lessons/

Content has been copied & pasted over from current lessons page.

**Comment by tobyhodges** [comment]
* Please add links to the text "Data Carpentry’s lessons" and "Library Carpentry’s lessons"
* Please adjust "These lessons are not part of Software Carpentry core lessons but can be offered as supplementary lessons" to "These lessons are not part of the core Software Carpentry curriculum but can be offered as supplementary lessons."
* "The CarpentriesLab" -> "The Carpentries Lab"

**Comment by maneesha** [comment]
Changes have been made.  @tobyhodges Please review. If it looks good, you can close this issue. Otherwise share any other comments here.
 https://swc-new-website.netlify.app/lessons/

**Comment by tobyhodges** [comment]
On reflection, now that we have removed the "Materials in Early Development" section from the DC lessons page (https://github.com/datacarpentry/new-website/issues/42), I would prefer to do the equivalent here and also remove the section titled "Community Developed Lessons" from this page. Sorry for the confusion.

After that change has been made, I am happy for this issue to be closed.
