### ISSUE TITLE
Footer description text

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/new-website#38]
We have placeholder language in the footer.

> Software Carpentry is a lesson program of The Carpentries. Cake pastry candy carrot cake croissant tootsie roll chocolate bar dragée cotton candy.

What language should actually go there?

**Comment by OscarSiba** [comment]
Please simply leave this as "Software Carpentry is a lesson program of The Carpentries."

**Comment by maneesha** [comment]
Fixed with #43
