### ISSUE TITLE
Stle changes to SWC website

### ISSUE THREAD

**Issue by OscarSiba** [swcarpentry/new-website#52]
### How could the content be improved?

**Software Carpentry**: https://swc-new-website.netlify.app/about-us/
- [x] Please retitle this to be "About us". Please compare to same page on LC and DC sites. 
- [x] Please also add the "Subscribe to our newsletter" button here. 
- [x] In the second paragraph, please hyperlink "Having started in 1998" to this link: https://carp-new-website.netlify.app/about-us/#our-history
- [x] In the second paragraph, please write the number "100,000" as part of the bit that says "almost one hundred thousand people". 
- [x] The very last sentence reads 'please see “Software Carpentry: Lessons Learned”'. Please revise this to say: "please read [Software Carpentry: Lessons Learned](https://carpentries.org/blog/2013/06/lessons-learned/)."

**Software Carpentry Lessons**: https://swc-new-website.netlify.app/lessons/

In the introductory paragraph:
- [x] Please spell instructor and instructors with a capital "I".
- [x] Please spell organization and visualization with "s" instead of "z".

**Software Carpentry Curriculum Advisors**: https://swc-new-website.netlify.app/about-us/curriculum-advisors/

- [x] Please separate the last sentence from the rest, and skip a line, so that it stands out.

**Comment by OscarSiba** [comment]
Tagging you here @maneesha as I can't seem to be able to assign the issue to you.

**Comment by maneesha** [comment]
Addressed with #53
